language: ruby

rvm:
  - jruby-1.7.19
  - jruby-head

jdk: openjdk7

services:
  - redis

addons:
  postgresql: 9.3

cache: bundler

sudo: false

env:
  global:
    - COVERAGE=1
  matrix:
    - RAKE_TASK=spec
    - RAKE_TASK=rubocop

before_script:
  - 'RAILS_ENV=test bundle exec rake db:create db:structure:load --trace'

script: ./build.sh $RAKE_TASK

matrix:
  allow_failures:
    - rvm: jruby-head
      env: RAKE_TASK=rubocop
    - rvm: jruby-1.7.19
      env: RAKE_TASK=rubocop
    - rvm: jruby-head
      env: RAKE_TASK=spec
