language: ruby

rvm: jruby-1.7.6

jdk: openjdk7

services:
  - redis

before_script:
  - 'RAILS_ENV=test rake db:create db:schema:load --trace'

script: ./build.sh

notifications:
  irc: "irc.freenode.org#travis"
