language: ruby

rvm: jruby-1.7.12

jdk: openjdk7

services:
  - redis

addons:
  postgresql: 9.3

before_script:
  - 'RAILS_ENV=test bundle exec rake db:create db:structure:load --trace'

script: ./build.sh

notifications:
  irc: "irc.freenode.org#travis"
